# Generated by Django 5.0.4 on 2024-04-15 05:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.CharField(max_length=255, verbose_name="Question")),
            ],
            options={
                "verbose_name": "Form question",
                "verbose_name_plural": "Form questions",
            },
        ),
        migrations.CreateModel(
            name="FormResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "Form Result",
                "verbose_name_plural": "Form Results",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.CharField(verbose_name="Question")),
                (
                    "question_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("text", "Text"),
                            ("date", "Date"),
                            ("number", "Number"),
                            ("radio", "Radio"),
                            ("tel", "Telephone"),
                            ("option", "Option"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Question type",
                    ),
                ),
                (
                    "hidden",
                    models.BooleanField(default=False, verbose_name="Hide from forms"),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(verbose_name="Stage name")),
            ],
            options={
                "verbose_name": "Stage",
                "verbose_name_plural": "Stages",
            },
        ),
        migrations.CreateModel(
            name="FormAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answer", models.CharField(max_length=255, verbose_name="Answer")),
                (
                    "form_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_questions",
                        to="core.formquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form answer",
                "verbose_name_plural": "Form answers",
            },
        ),
        migrations.CreateModel(
            name="FormStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Form stage title"),
                ),
                (
                    "form_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.formresult",
                    ),
                ),
                (
                    "parent_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_results",
                        to="core.formresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form stage",
                "verbose_name_plural": "Form stages",
            },
        ),
        migrations.CreateModel(
            name="FormSubStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Form sub stage title"
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_stages",
                        to="core.formstage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form sub stage",
                "verbose_name_plural": "Form sub stages",
            },
        ),
        migrations.AddField(
            model_name="formquestion",
            name="form_sub_stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="form_sub_stage",
                to="core.formsubstage",
            ),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answer", models.CharField(verbose_name="Answer")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="core.question",
                        verbose_name="Question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer",
                "verbose_name_plural": "Answers",
            },
        ),
        migrations.CreateModel(
            name="SubStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(verbose_name="Sub Stage name")),
                (
                    "parent_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="core.stage",
                        verbose_name="Stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub Stage",
                "verbose_name_plural": "Sub Stages",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="sub_stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_stages",
                to="core.substage",
                verbose_name="Sub Stage",
            ),
        ),
    ]
